// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMcRjKPPY1_vpJvMV5Ab6qUJoFcD1SV74',
    appId: '1:1038793941953:web:3756c7121f2d3acece8540',
    messagingSenderId: '1038793941953',
    projectId: 'migii-sat',
    authDomain: 'migii-sat.firebaseapp.com',
    storageBucket: 'migii-sat.appspot.com',
    measurementId: 'G-813DNK347F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9h3DlZYsRXI7h6fVGKelQFlVW60fQ0U',
    appId: '1:1038793941953:android:eaeb8a6d4a6db146ce8540',
    messagingSenderId: '1038793941953',
    projectId: 'migii-sat',
    storageBucket: 'migii-sat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcbPFUd06JfD246Bo0inT0ymXXE-2gl1c',
    appId: '1:1038793941953:ios:91cc809c5731c935ce8540',
    messagingSenderId: '1038793941953',
    projectId: 'migii-sat',
    storageBucket: 'migii-sat.appspot.com',
    iosClientId: '1038793941953-hj8sf7d83knfklj3r9dqg94fnu8eqgnl.apps.googleusercontent.com',
    iosBundleId: 'com.eup.migiisat',
  );
}
